spring:
  profiles:
    active: pro
  datasource:
    driver-calss-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl
    username: root
    password: 132152
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

